armor.register_item("iron",{
	type="chestplate",
	image="default_ironblock.png",
	level=10,
	item="default:iron_ingot",
})
armor.register_item("iron",{
	type="helmet",
	image="default_ironblock.png",
	level=8,
	item="default:iron_ingot",
})
armor.register_item("iron",{
	type="boots",
	image="default_ironblock.png",
	level=7,
	item="default:iron_ingot",
})
armor.register_item("iron",{
	type="leggings",
	image="default_ironblock.png",
	level=8,
	item="default:iron_ingot",
})
armor.register_item("iron",{
	type="gloves",
	image="default_ironblock.png",
	level=5,
	item="default:iron_ingot",
})